### ISSUE TITLE
Doesn't appear to be working..

### ISSUE THREAD

**Issue by richardclick** [mapk/SM-Scaffold#2]
So not totally sure how this is supposed to work, but my guess was: 1 --> create new file in Figma, 2 --> click SM Scaffold in plugin menu. 

It says 'running SM scaffold' in the bottom notification but the only thing it does is create the '- cover -' page and then never ever finishes 'running sm scaffold'.

Looking forward to using it. Thanks!!

**Comment by mapk** [comment]
Could not replicate this problem. We're updating it a bit as well.
